title: "Home Buns"
email: info@homebuns.com
timezone: America/Costa_Rica
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/brand/home-buns-logo.png'
favicon: 'assets/images/favicon.ico'
author: Adrian Robles
locale: es_CR
lang: es-CR
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
url: "https://www.homebunscr.com"
description: "Panes artesanales para hamburguesas, choripanes, subs y creaciones gastronómicas en Costa Rica."

# Social
social:
  instagram: https://www.instagram.com/homebunscr/
  facebook: https://www.facebook.com/homebuns

whatsapp: "50687510210"

plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
